//
// Created by tsbertalan on 7/15/18.
//
#include "parameters.h"


// PLANNER
int NUM_PLANS = 128;
bool SHOW_COSTS_TABLE = false;
bool LOGGING = false;
bool DEBUG = false;

double MIPH_TO_MPS = (5280/1.)*(1./3.2808)*(1/3600.);

double GOAL_SPEED_MPH = 47;
double MAX_TARGET_SPEED = (GOAL_SPEED_MPH + 1) * MIPH_TO_MPS;
double MIN_TARGET_SPEED = 1;
double MAX_SPEED_DIFFERENCE = 20;
double MIN_SPEED_DIFFERENCE = -MAX_TARGET_SPEED + 1;
double EXT_TIME = 1;

double MIN_REUSE_TIME = 32 * .02;
double MIN_DT = 2;

double MAX_DT = 3;
double LANE_DEFINITION_LEFT = 2.1;
double LANE_DEFINITION_CENTER = 6;
double LANE_DEFINITION_RIGHT = 9.8;

// TRAJECTORY GENERATION
bool DO_CACHE = true;

// COST
double FACTOR_DISTANCE = 10;

double CAR_WIDTH = (116. - 10) * 4. / 176.;
double CAR_LENGTH = 214. * 4. / 176.;

double PENALTY_FATAL = 10;

double DISTANCE_ZERO_COST_FOLLOW = -6 * CAR_LENGTH;
double DISTANCE_ZERO_COST_LEAD = 3 * CAR_LENGTH;
double DISTANCE_ZERO_COST_BESIDE = .189 * CAR_WIDTH;

double FACTOR_ACCEL = 1./24.;
double FACTOR_JERK = 1./96.;

double FACTOR_SPEED_EXCESS = 4;
double CRITICAL_SPEED_EXCESS = 49.5 * MIPH_TO_MPS;

double FACTOR_ACCEL_EXCESS = 4;
double CRITICAL_ACCEL_EXCESS = 9;

double FACTOR_JERK_EXCESS = 4;
double CRITICAL_JERK_EXCESS = 9;

double GOAL_SPEED = GOAL_SPEED_MPH*MIPH_TO_MPS;

double SPEED_LIMIT = 50 * MIPH_TO_MPS;
double VDEV_MID = -15 * MIPH_TO_MPS;
double SPEED_COST_ZERO = 2;
double SPEED_COST_MID = 1.5;
double SPEED_COST_LIMIT = 6;
double FACTOR_VDEV = .5;

double FACTOR_LANE_SW = .01;

double CRITICAL_SWITCHTIME = 3000;

double SCALE_SWITCHTIME = .01;
double FACTOR_FASTSW = .8;
double FACTOR_CRP = .003;

double PENALTY_LANE_LEFT = .1;
double PENALTY_LANE_CENTER = 0;
double PENALTY_LANE_RIGHT = .1;
double PENALTY_LINE_SOLID = 2;
double PENALTY_LINE_DASHED = .5;
double PENALTY_OFF_ROAD = 10;

double BAD_MAP_BEGIN = 4900;
double BAD_MAP_END = 5080;
double BAD_MAP_DRIFT_LEFT = -.25;

// VISUALIZESR
double COST_VIZ_CAP = 10.;
int NUM_PLANS_VISUALIZED = 20;
double VIS_S_THRESHOLD = CAR_LENGTH*2;
